### ISSUE TITLE
problem when skipping order?

### ISSUE THREAD

**Issue by j-faria** [Kamuish/serval#17]
I got this error:

```python
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    builder()
  File "/home/jfaria/Software/serval/src/serval.py", line 2250, in builder
    serval()
  File "/home/jfaria/Software/serval/src/serval.py", line 1371, in serval
    smod, ymod = spl.ucbspl_fit(wmod[ind], mod[ind], we[ind], K=nk, lam=pspllam, mu=mu, e_mu=e_mu, e_yk=True, retfit=True)
  File "/home/jfaria/Software/serval/src/cspline.py", line 502, in ucbspl_fit
    if xmin is None: xmin = x.min()
  File "/home/jfaria/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
```

after a warning of  
"too many negative data points in n=0, o=7, RV=1.1118432088151629; skipping order"

so I think the two are related

**Comment by Kamuish** [comment]
I am yet to be able to reproduce this... I am finding some problems on the analyse_rv function, due to the error that we have discussed today. I am going to look into the original implementation to understand  exactly what is going on there. 

Afterwards, I will come back to this

**Comment by Kamuish** [comment]
@j-faria  I found a problem with the logger configuration and thus, there was a lot of information missing. It should all be fixed now (or if not, an error will be sent through the terminal).

 If possible, could you reproduce the error and see if anything else pops up?

**Comment by Kamuish** [comment]
On the py2 version the .daterr file actually has two lines (when running with 2 files). High possibility of being a bug with the output creation portion.

**Comment by Kamuish** [comment]
The creation of the outputs is made by writing after each epoch is processed. The files were created with the 'w' mode, thus we did not have the correct shape on the inputs of the analyse rv function.

HOWEVER, take note that this change will probably be problematic if we are running the code for the second time over the same data set (as we are currently doing). Thus, just to be sure, I will update run.py to clean the gj699 folder.

I will try to check if this is done inside serval, but I would guess not, since there is an "info" log mentioning that there is data being collected from that folder

**Comment by Kamuish** [comment]
@j-faria After fixing the output files I tried running over the entire gj699 data set. I did not get the same error. Could you please try and see if you can reproduce it?

**Comment by j-faria** [comment]
seems to be fixed :man_shrugging:
