### ISSUE TITLE
compare with serval @ py2

### ISSUE THREAD

**Issue by j-faria** [Kamuish/serval#19]
use gj699 and diff output files

**Comment by Kamuish** [comment]
Preliminary differences (using -brvref DRS)

1. gnuplot appears to be working properly (without the screen flicker we found in py3). This probably means that it is very likely we will have to do #20  . In py2 the pauses work and thus we do not see it as we were seeing

2. Python2 version is producing .bad files. Python3 not... They are created if the rvflag is set to 1, in serval.py line 2102

3. for now I have only looked into the rvc.dat and the brv.dat. The first one, rvc, appears to be equal between both versions ( the first column has an higher precision that py2 version). BRV.dat only has a line on py3, versus the 10 lines of py2. Seems to suggest that there is a write routine with mode 'w' instead of mode 'a'.

**Comment by Kamuish** [comment]
More information 

1. Point 3 of previous comment has been solved
2. With the use o np.allclose and rtol = 1e-3, the only difference found in the outputs files resides in the post.dat file, which is, accordingly to the documentation: <'obj.post.dat   post processed RVs with re-weighting of orders (experimental)'>
3. Still missing the .fits files

**Comment by j-faria** [comment]
same results for ESPRESSO data

**Comment by Kamuish** [comment]
Updates:

1. the .post.dat file is created on line 245, serval.py. It is created with np.savetxt... weird to not be saving a string... 
2. for gj699, the fits files are all equal with a rtol of 1e.3 -> outputs seem to be working as expected
3. Still missing the rv flag that is different on both versions. As I have said, I would guess it's something to do with the bitwise operations that are then converted to an integer... I will check tomorrow

**Comment by j-faria** [comment]
all outputs are the same
issue with "bad" files is fixed: we were being dumb...
